on: 
  push:
    branches:
    - master

jobs:
  FTP-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload FTP
      uses: sebastianpopp/ftp-action@v1.0.0
      with: 
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: "www/projetTUT"
